// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj5g0JJHvT_Ck-Dk8pj0rblqbEXn-F0EY',
    appId: '1:571549908150:web:886bfb5307d1e655303a17',
    messagingSenderId: '571549908150',
    projectId: 'barcode-scanner-f32fe',
    authDomain: 'barcode-scanner-f32fe.firebaseapp.com',
    storageBucket: 'barcode-scanner-f32fe.firebasestorage.app',
    measurementId: 'G-0N6NE9NEGR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYvEj-pd8QIu_gqz5gUW7uypiif0QSC-8',
    appId: '1:571549908150:android:eb5eee408e3cab19303a17',
    messagingSenderId: '571549908150',
    projectId: 'barcode-scanner-f32fe',
    storageBucket: 'barcode-scanner-f32fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBviWtN_Ziuj6wOgpfEeNdb6a-AtKw915w',
    appId: '1:571549908150:ios:2174efd94e88ae3c303a17',
    messagingSenderId: '571549908150',
    projectId: 'barcode-scanner-f32fe',
    storageBucket: 'barcode-scanner-f32fe.firebasestorage.app',
    iosClientId: '571549908150-qvmlpra1prehqqppb901blt8sv2ek395.apps.googleusercontent.com',
    iosBundleId: 'com.example.barcode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBviWtN_Ziuj6wOgpfEeNdb6a-AtKw915w',
    appId: '1:571549908150:ios:2174efd94e88ae3c303a17',
    messagingSenderId: '571549908150',
    projectId: 'barcode-scanner-f32fe',
    storageBucket: 'barcode-scanner-f32fe.firebasestorage.app',
    iosClientId: '571549908150-qvmlpra1prehqqppb901blt8sv2ek395.apps.googleusercontent.com',
    iosBundleId: 'com.example.barcode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCj5g0JJHvT_Ck-Dk8pj0rblqbEXn-F0EY',
    appId: '1:571549908150:web:c51495aff72a9381303a17',
    messagingSenderId: '571549908150',
    projectId: 'barcode-scanner-f32fe',
    authDomain: 'barcode-scanner-f32fe.firebaseapp.com',
    storageBucket: 'barcode-scanner-f32fe.firebasestorage.app',
    measurementId: 'G-W5QKMS60VR',
  );
}
